### ISSUE TITLE
Fraction. Función isEquivalent()

### ISSUE THREAD

**Issue by robertome** [robertome/IWVG.SwC.RobertoMartin#5]
Función isEquivalent()

[Detalle](https://github.com/robertome/IWVG.SwC.RobertoMartin/wiki/Fraction#ampliaci%C3%B3n-2-funci%C3%B3n-isequivalent)

**Comment by albertogarciag95** [comment]
Done!

**Comment by albertogarciag95** [comment]
Cerrada por error, reabro. Sorry!
