### ISSUE TITLE
Fraction. Funciones isGreaterThan(Fraction) e isLowerThan(Fraction)

### ISSUE THREAD

**Issue by robertome** [robertome/IWVG.SwC.RobertoMartin#6]
Funciones `isGreaterThan(Fraction)` e `isLowerThan(Fraction)`

[Detalle](https://github.com/robertome/IWVG.SwC.RobertoMartin/wiki/Fraction#ampliaci%C3%B3n-3-funciones-isgreaterthanfraction-e-islowerthanfraction)

**Comment by alexph9** [comment]
Done!
